name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Display current version
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout

    - name: Update version
      run: |
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $CURRENT_VERSION"
        NEW_VERSION=$(echo $CURRENT_VERSION | sed 's/-SNAPSHOT//' | awk -F'.' '{printf "%d.%d.%d", $1, $2, $3+1}')
        echo "New version: $NEW_VERSION"
        mvn versions:set -DnewVersion=$NEW_VERSION
        mvn versions:commit
        echo "Updated version in POM:"
        cat pom.xml | grep "<version>"

    - name: Get project version
      id: project_version
      run: |
        NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Setting output VERSION to $NEW_VERSION"
        echo "::set-output name=VERSION::$NEW_VERSION"

    - name: Build with Maven
      run: mvn clean package

    - name: Get JAR file name
      id: jar_name
      run: echo "::set-output name=JAR_NAME::$(ls target | grep '.jar$')"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 \
        --build-arg JAR_FILE=target/${{ steps.jar_name.outputs.JAR_NAME }} \
        --tag dinbl/java_app:${{ steps.project_version.outputs.VERSION }} \
        --push .

