name: Maven Package

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github 
          settings-path: ${{ github.workspace }} 

      - name: Install Maven 3.9.2
        run: |
          wget https://archive.apache.org/dist/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
          tar -xzf apache-maven-3.9.2-bin.tar.gz
          sudo mv apache-maven-3.9.2 /usr/local/apache-maven
          sudo rm /usr/bin/mvn
          sudo ln -s /usr/local/apache-maven/bin/mvn /usr/bin/mvn

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from git tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/my-app
          flavor: latest=true
          prefix: refs/tags/
          sort: semver
          tags: type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-app:latest
            ${{ secrets.DOCKER_USERNAME }}/my-app:${{ steps.meta.outputs.version }}

      - name: Set git remote URL
        run: git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/${{ secrets.GIT_USERNAME }}/Java-Maven-App.git

      - name: Tag and push new version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ steps.meta.outputs.version }}" -m "Release ${{ steps.meta.outputs.version }}"
          git push origin "${{ steps.meta.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
